config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#landing"
  get "/my_events", to: "users#home", as: :my_events
  resources :users, only: %i[show update edit] do
    resources :friends, only: %i[index update]
    post '/friends', to: 'friends#create', as: :friends_add
  end
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: %i[create]
  end
  resources :events do
    resources :participants, only: %i[create update]
    resources :posts, except: %i[index show edit new]
  end
  resources :posts, only: [] do
    resources :comments, only: %i[create update]
  end
  resources :comments, only: :destroy
  resources :participants, only: :destroy
  resources :likes, only: %i[create destroy]
  resources :friends, only: %i[destroy]
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :asker, class_name: "User"
  belongs_to :receiver, class_name: "User"
  has_one :chatroom, dependent: :destroy
  validates_uniqueness_of :asker_id, scope: :receiver_id

  # validates :asker_id, uniqueness: { scope: :receiver_id, message: "There is an invitation already!" }

   def receivers_list
    @friends = User.where.not(id: current_user.id)
   end
  def self.reacted?(id1, id2)
    case1 = !Friend.where(asker_id: id1, receiver_id: id2).empty?
    case2 = !Friend.where(asker_id: id2, receiver_id: id1).empty?
    case1 || case2
  end

  def self.confirmed_record?(id1, id2)
    case1 = !Friend.where(asker_id: id1, receiver_id: id2, confirmed: true).empty?
    case2 = !Friend.where(asker_id: id2, receiver_id: id1, confirmed: true).empty?
    case1 || case2
  end

  def self.find_invitation(id1, id2)
    if Friend.where(asker_id: id1, receiver_id: id2, confirmed: true).empty?
      Friend.where(asker_id: id2, receiver_id: id1, confirmed: true)[0].id
    else
      Friend.where(asker_id: id1, receiver_id: id2, confirmed: true)[0].id
    end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = Friend.all
    @user = current_user
  end

  def create
    @asker_id = current_user
    @receiver_id = User.find(params[:user_id].to_i)
    @friend = Friend.new(asker: @asker_id, receiver: @receiver_id)
    if Friend.reacted?(@friend.asker_id, @friend.receiver_id) == false && Friend.confirmed_record?(@friend.asker_id, @friend.receiver_id) == false
      @friend.save
      Chatroom.create(friend_id: @friend.id)
      flash.alert = "Invitation sent!"
    elsif @friend.valid? == false && Friend.confirmed_record?(@friend.asker_id, @friend.receiver_id) == false
      flash.alert = "There is an invitation already sent!"
    else
      flash.alert = "You are already a friend!"
    end
    redirect_to user_path(params[:user_id])
  end

  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy
    redirect_to user_friends_path(current_user)
  end

  def update
    @user = User.find(params[:user_id])
    @friend = Friend.find(params[:id])
    @friend.confirmed = true
    @friend.save
    redirect_to user_friends_path(current_user)
  end

  private

  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :receiver_id)
  end
  ################################ DEIXAR PRA DEPOIS ###################################
end

app/views/friends/_friend.html.erb
<div class="container">
  <%= simple_form_for [@user, @friend] do |f| %>
        <%# <%= f.input :first_name %>
        <%= f.association :receiver, collection: User.where.not(id: current_user.id), label_method: :full_name %>
          <%= f.submit 'Create', class: "btn btn-primary" %>
      <% end %>

  <!-- Mostrar todos os amigos -->
  <h2>Your Friends</h2>
  <ul>
    <% @friends.each do |friend| %>
      <li><% if friend.confirmed == true %>
            <%if friend.asker_id != current_user.id %>
              <% @user = User.find(friend.asker_id) %>
              <%= cl_image_tag @user.avatar.key, class: "avatar-large" %>
              <%= link_to "Unfriend", friend_path(friend),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
              <% if Chatroom.find_by(friend_id: friend.id) != nil %>
                <%= link_to "Chat", chatroom_path(Chatroom.find_by(friend_id: friend.id))%>
              <% end %>
            <% else %>
              <% @user = User.find(friend.receiver_id) %>
              <%= cl_image_tag @user.avatar.key, class: "avatar-large" %>
              <%= link_to "Unfriend", friend_path(friend),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
              <% if Chatroom.find_by(friend_id: friend.id) != nil %>
                <%= link_to "Chat", chatroom_path(Chatroom.find_by(friend_id: friend.id))%>
              <% end %>
            <% end %>
          <% end %>
      </li>
    <% end %>
  </ul>
  <h2>Your Requests</h2>
  <ul>
    <% @friends.each do |friend| %>
      <li><%if friend.asker_id != current_user.id && friend.confirmed == false %>
              <% @user = User.find(friend.asker_id) %>
              <%= cl_image_tag @user.avatar.key, class: "avatar-large" %>
              <%= @user.full_name %>
              <%= button_to "accept this friendship", [current_user, friend], method: 'patch'  %>
          <% end %>
      </li>
    <% end %>
  </ul>

</div>

app/views/friends/index.html.erb
<div class="friend-grid">
  <div class="bg-friend-list-cards">
    <div>
      <h2 class= "text-center my-3">My Friends</h2>
        <ul class="row">
          <% @friends.each do |friend| %>
            <% if friend.confirmed == true %>
              <%if friend.asker_id == current_user.id %>
                <li class="list-friends">
                  <% @user = User.find(friend.receiver_id) %>
                  <%= cl_image_tag @user.avatar.key, class: "avatar-friend" %>
                  <p class="text-center mt-5"><strong><%= @user.full_name %></strong></p>
                  <%= link_to friend_path(friend),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do%>
                    <i class="fa-solid fa-user-minus fa-xl text-danger delete-friend"></i>
                  <% end %>
                  <% if Chatroom.find_by(friend_id: friend.id) != nil %>
                    <%= link_to chatroom_path(Chatroom.find_by(friend_id: friend.id)) do%>
                      <i class="fa-solid fa-message fa-xl chat-icon"></i>
                    <% end %>
                  <% end %>
                </li>
              <% elsif  friend.receiver_id == current_user.id%>
                <li class="list-friends ">
                  <% @user = User.find(friend.asker_id) %>
                  <%= cl_image_tag @user.avatar.key, class: "avatar-friend" %>
                  <p class="text-center mt-5"><strong><%= @user.full_name %></strong></p>
                  <%= link_to friend_path(friend),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do%>
                    <i class="fa-solid fa-user-minus fa-xl text-danger delete-friend"></i>
                  <% end %>
                  <% if Chatroom.find_by(friend_id: friend.id) != nil %>
                    <%= link_to chatroom_path(Chatroom.find_by(friend_id: friend.id)) do%>
                      <i class="fa-solid fa-message fa-xl chat-icon"></i>
                    <% end %>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          <% end %>
        </ul>
    </div>
  </div>
  <div class="bg-friend-list-requests">
    <h2 class= "text-center my-3">My Requests</h2>
      <ul class="list-request">
        <% @friends.each do |friend| %>
          <li class="d-flex flex-row">
            <% if friend.confirmed == false %>
              <% if friend.asker_id == current_user.id %>
                <% @user = User.find(friend.receiver_id) %>
                <%= cl_image_tag @user.avatar.key, class: "avatar-friend" %>
                <p class="friend-name"><%= @user.full_name %></p>
              <% elsif friend.receiver_id == current_user.id  %>
                <% @user = User.find(friend.asker_id) %>
                <%= cl_image_tag @user.avatar.key, class: "avatar-friend" %>
                <p class="friend-name"><%= @user.full_name %></p>
                <%= button_to [current_user, friend], class: "bg-check", method: 'patch' do %>
                  <i class="addfriend fa-solid fa-check fa-2xl" style="color: #3ade0d;"></i>
                <% end %>
                <%= link_to friend_path(friend),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do  %>
                  <i class="fa-solid fa-ban delete-request fa-2xl" style="color: #d31212;"></i>
                <% end %>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>
  </div>
</div>