config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#landing"
  get "/my_events", to: "users#home", as: :my_events
  resources :users, only: %i[show update edit] do
    resources :friends, only: %i[index update]
    post '/friends', to: 'friends#create', as: :friends_add
  end
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: %i[create]
  end
  resources :events do
    resources :participants, only: %i[create update]
    resources :posts, except: %i[index show edit new]
  end
  resources :posts, only: [] do
    resources :comments, only: %i[create update]
  end
  resources :comments, only: :destroy
  resources :participants, only: :destroy
  resources :likes, only: %i[create destroy]
  resources :friends, only: %i[destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :participants
  has_many :likes
  has_many :posts
  has_many :events_as_participant, through: :participants, source: :event
  has_many :friends_as_asker, class_name: "Friend", foreign_key: :asker_id
  has_many :friends_as_receiver, class_name: "Friend", foreign_key: :receiver_id
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :events
  has_many :messages
  has_one_attached :avatar
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit show]

  def home
    @events = Event.where(user_id: current_user.id)
    @events_home = []
    @events_days = []
    @participants = Participant.where(user_id: current_user)
    @participants.each do |participant|
      @events_home << Event.find(participant.event_id)
    end
    @events_location = Event.near([current_user.latitude, current_user.longitude], 200).limit(5)
  end

  def show
    @friends = Friend.all
    @friend = Friend.new
    @event = Event.find(@user.event_ids.first)
  end

  def landing
  end

  def edit
    @user = User.new
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :address)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<h1>user edit</h1>

app/views/users/home.html.erb
<div class="user-home-page d-flex flex-column mt-4">
  <%# SUGGESTED EVENTS CAROUSEL %>
  <h2 class="d-flex justify-content-center"> Events near you </h2>
  <div class="carousel d-flex justify-content-center">
    <div class="carousel-cards">
      <% @events_location.each do |event| %>
          <div class="card"><%= link_to event_path(event) do %>
            <h3 class="title"><%= event.title %></h3>
              <div class="card-image" style="background-image: linear-gradient(rgba(255, 0, 0, 0), rgba(0, 0, 0, 0.8)), url('<%=cl_image_path event.photo.key%>');
                          background-size: cover;
                          width: 100%;
                          background-position: center;">
              </div>
            <% end %>
          </div>
      <% end %>
    </div>
  </div>

  <div class="centered-container">
    <%= link_to "See more events", events_path, class: "event-list-link" %>
  </div>
  <%# MY EVENTS CARDS %>
    <div class="next-events">
    <h2 class="home-sub-heading">My Created Events</h2>
    <div class="events-cards-grid">
      <% @events.select { |event| (event.event_date - Date.today).to_i >= 0 }
                  .sort_by { |event| (event.event_date - Date.today).to_i }
                  .each do |event| %>
        <%= link_to event_path(event) do %>
          <div class="next-event-card">
            <div class="card-img" style="background-image: linear-gradient(rgba(255, 0, 0, 0), rgba(0, 0, 0, 0.8)), url('<%=cl_image_path event.photo.key%>')"></div>
            <div class="card-info">
              <h4><strong><%= event.title %></strong></h4>
              <h5><%= event.event_date.strftime("%B ") + event.event_date.day.ordinalize %></h5>
              <% if (event.event_date - Date.today).to_i.zero? %>
                <p><em><strong style="color: #4CAF50;">Today!</strong></em></p>
              <% elsif (event.event_date - Date.today).to_i > 0 %>
                <p><em>in <strong style="color: red;"><%= (event.event_date - Date.today).to_i %></strong> days</em></p>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <%# NEXT EVENTS CARDS %>
  <div class="next-events">
    <h2 class="home-sub-heading">Upcoming Events</h2>
    <div class="events-cards-grid">
      <% @events_home.select { |event| (event.event_date - Date.today).to_i >= 0 }
                  .sort_by { |event| (event.event_date - Date.today).to_i }
                  .each do |event| %>
        <%= link_to event_path(event) do %>
          <div class="next-event-card">
            <div class="card-img" style="background-image: linear-gradient(rgba(255, 0, 0, 0), rgba(0, 0, 0, 0.8)), url('<%=cl_image_path event.photo.key%>')"></div>
            <div class="card-info">
              <h4><strong><%= event.title %></strong></h4>
              <h5><%= event.event_date.strftime("%B ") + event.event_date.day.ordinalize %></h5>
              <% if (event.event_date - Date.today).to_i.zero? %>
                <p><em><strong style="color: #4CAF50;">Today!</strong></em></p>
              <% elsif (event.event_date - Date.today).to_i > 0 %>
                <p><em>in <strong style="color: red;"><%= (event.event_date - Date.today).to_i %></strong> days</em></p>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/landing.html.erb
<%# SESSION 1 %>
<div class="session1 d-flex justify-content-between flex-column">
  <div class="img_landing1_parent d-flex align-items-center">
    <div class="session-text h2-text px-5">
      <h1 class="session-heading display-1"><strong>Together, We Make a Difference</strong></h1>
      <h2 class="subheading"><em>Uniting Communities to Help the Homeless</em></h2>
      <br>
      <h3 class="session-description">Promote upcoming volunteer events and opportunities, such as serving meals at a shelter or participating in a community cleanup.</h3>
    </div>
    <img src="https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" alt="" class="img_landing1">
  </div>
  <a href="#session-2"><div class="arrow bounce"></div></a><br />
</div>

<%# SESSION 2 %>
<div class="session2 d-flex justify-content-between flex-column" id="session-2">
  <div class="img_landing1_parent d-flex align-items-center">
    <div class="session-text h2-text px-5 order-2">
      <h2 class="session-heading display-2 mb-4"><strong>Volunteer Opportunities</strong></h2>
      <h3 class="session-description">Run campaigns to collect essential items such as blankets, clothing, toiletries, or non-perishable food items for homeless individuals.</h3>
    </div>
    <img src="https://images.unsplash.com/photo-1604176354204-9268737828e4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=580&q=80" alt="" class="img_landing1 order-1">
  </div>
  <a href="#session-3"><div class="arrow bounce"></div></a><br />
</div>

<%# SESSION 3 %>
<div class="session3 d-flex justify-content-between">
  <div class="img_landing1_parent d-flex align-items-center">
    <div class="session-text h2-text px-5">
      <h2 class="session-heading display-2 mb-4"><strong>Engage with the Community</strong></h2>
      <br>
      <h3 class="session-description">Encourage people to share their own experiences or ideas for helping the homeless, fostering a sense of community and involvement.</h3>
      <%= link_to "Browse Events", events_path, class:"button-50 text-black" %>
    </div>
    <img src="https://images.unsplash.com/photo-1593113598332-cd288d649433?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" alt="" class="img_landing1">
  </div>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>
  <div class="profile-card d-flex justify-content-center">
    <div class="snip1336">
      <%=cl_image_tag @event.photo.key, class: "card-banner"%>
      <img><%=cl_image_tag @user.avatar.key, class: "profile"%><img>
      <div class="profile-info">
        <h2 class="profile-name" ><%= current_user.first_name %> <%=  current_user.last_name %></h2>
        <p class="address">Address: <%= current_user.address %></p>
      </div>
    </div>
  </div>
<% else %>
  <div class="profile-card d-flex justify-content-center">
    <div class="snip1336">
      <%=cl_image_tag @event.photo.key, class: "card-banner"%>
      <img><%=cl_image_tag @user.avatar.key, class: "profile"%><img>
      <div class="profile-info">
        <h2 class="profile-name"><%= @user.first_name %> <%=  @user.last_name %></h2>
        <div class="friend-interaction">
          <% if Friend.confirmed_record?(current_user, params[:id]) == true %>
            <%= link_to friend_path(Friend.find_invitation(current_user, params[:id])), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-solid fa-user-minus fa-xl text-danger delete-friend"></i>
            <% end %>
          <% else %>
            <%= button_to user_friends_add_path(params[:id]), class: "addfriend", method: :post do%>
              <i class="addfriend fa-solid fa-user-plus fa-2xl" style="color: #3ade0d;"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>