config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#landing"
  get "/my_events", to: "users#home", as: :my_events
  resources :users, only: %i[show update edit] do
    resources :friends, only: %i[index update]
    post '/friends', to: 'friends#create', as: :friends_add
  end
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: %i[create]
  end
  resources :events do
    resources :participants, only: %i[create update]
    resources :posts, except: %i[index show edit new]
  end
  resources :posts, only: [] do
    resources :comments, only: %i[create update]
  end
  resources :comments, only: :destroy
  resources :participants, only: :destroy
  resources :likes, only: %i[create destroy]
  resources :friends, only: %i[destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" id="session-3">
  <p class="contact-info position-absolute top-50 end-0 translate-middle">contact@helphomeless.site</p>
  <p class="footer-copyright position-absolute top-50 start-50 translate-middle">Copyright © 2023 HelpHomeless</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm color-comp navbar-lewagon" data-controller="refresh">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dtz9smyye/image/upload/v1686775605/FtLPAyz4_2x-removebg-preview_e2slpi.png" %>
  <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div data-refresh-target="search" class="d-none">
      <div class="row justify-content-center navbar_search">
        <%= form_with url: events_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query, params[:query], class: "form-control", style:"border: 1px solid black"%>
          <%= submit_tag "Search", name: "", class: "button-50 text-black p-2 mt-1 mx-2" %>
        <% end %>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <i class="fa-solid fa-magnifying-glass fa-2xl mx-3 text-black" data-action="click->refresh#toggle"></i>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.avatar.key.nil? %>
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag "https://img.freepik.com/free-icon/user_318-563642.jpg?w=360", class: "avatar-large", alt: "dropdown menu" %>
              </a>
            <% else %>
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= cl_image_tag current_user.avatar.key, class: "avatar-large" %>
              </a>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "New event", new_event_path, class: "dropdown-item" %>
              <%= link_to "My events", my_events_path, class: "dropdown-item" %>
              <%= link_to "Friends", user_friends_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>