config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#landing"
  get "/my_events", to: "users#home", as: :my_events
  resources :users, only: %i[show update edit] do
    resources :friends, only: %i[index update]
    post '/friends', to: 'friends#create', as: :friends_add
  end
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: %i[create]
  end
  resources :events do
    resources :participants, only: %i[create update]
    resources :posts, except: %i[index show edit new]
  end
  resources :posts, only: [] do
    resources :comments, only: %i[create update]
  end
  resources :comments, only: :destroy
  resources :participants, only: :destroy
  resources :likes, only: %i[create destroy]
  resources :friends, only: %i[destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: %i[title description], using: {
    tsearch: { prefix: true }
  }
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :participants
  has_many :users, through: :participants
  has_one_attached :photo
  geocoded_by :address

  validates :title, :description, :event_date, :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @events = Event.all
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR description ILIKE :query"
      @events = @events.where(sql_subquery, query: "%#{params[:query]}%")
    end
    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        id: event.id
      }
    end
    @user_location = {
      lat: current_user.latitude,
      lng: current_user.longitude,
      marker_html: render_to_string(partial: "marker")
    }
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @posts = Post.where(event_id: @event.id)
    @post = Post.new
    @participantdestroy = Participant.find_by(event_id: params[:id], user_id: current_user)
    @participant = Participant.new
    @participants = Participant.where(event_id: @event.id)
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to root
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :event_date, :address, :photo)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_marker.html.erb
<%= image_tag "mapbox-marker-icon-20px-orange.png", height: 70, width: 30, alt: "Logo" %>

app/views/events/index.html.erb
<div class="container2 show-events" >
  <div class="my-2 show-events-cards style="gap: 0 10px;">
    <% @events.each do |event| %>
      <div class="card my-3">
        <div class="row h-100 w-100">
          <div class="col-6 p-0">
            <div style="background-image: url('<%= cl_image_path event.photo.key%>');
                        background-size: cover;
                        height: 100%;
                        width: 100%;
                        background-position:center;"></div>
          </div>
          <div class="col-6 card-body">
            <h5 class="card-title"><%= event.title%></h5>
            <p class="card-text"><%= event.event_date %></p>
            <%= link_to "See more", event_path(event), class:"button-50 position-absolute bottom-0 end-0 p-1"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div id='map' class="col-4 m-4 w-100" data-controller="map" data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"  data-map-user-location-value="<%= @user_location.to_json %>" data-map-target="show_map">
  </div>
</div>

app/views/events/new.html.erb
<div class="new-grid">
  <div></div>
  <div class="container-events-new">
    <div class="page-heading-form my-4">
    <h1 class="page-heading display-5">New Event</h1>
    </div>
    <div class="event-form-group">
      <%= simple_form_for @event do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :event_date, label: "Date", as: :date, input_html: { class: 'form-control', value: Date.today.to_s }, html5: true %>
        <%= f.input :address %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'Create', class: "button-50" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="">
  <div class="event-show-display-grid p-5 mx-5  justify-content-left mt-5">
    <div class="d-inline-flex align-items-center px-4">
      <img> <%= cl_image_tag @event.photo.key, class: "img-fluid"%> <img>
    </div>
    <div class=" event-show-display-text p-4">
      <h1 class="mb-4"><strong><%= @event.title %></strong></h1>
      <h4><%= @event.description %></h4>
      <br>
      <h4 class="my-3"><strong>Event date:</strong> <%= @event.event_date.strftime("%B ") + @event.event_date.day.ordinalize + @event.event_date.strftime(" %Y") %></h4>
      <h4 class="my-4"><strong>Address:</strong> <%= @event.address %></h4>
      <% if @event.user_id != current_user.id %>
        <% if !@participantdestroy.nil? %>
            <%= link_to "Leave Event", participant_path(@participantdestroy), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"button-50-red" %>
          <% else %>
            <%= simple_form_for [@event, @participant] do |f| %>
            <%= f.button :submit, 'Join Event', class: "button-50" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="p-5 mx-5">
    <div class="row">
      <div class="col-8">
        <div class="card">
          <div class="card-body">
            <h2>Add a post</h2>
            <%= simple_form_for [@event, @post] do |f| %>
              <%= f.input :content, label: false %>
              <%= f.submit class: "button-50" %>
            <% end %>
            <h4>Posts</h4>
            <div class="comments-container">
              <ul id="comments-list" class="comments-list">
                <li>
                  <% @posts.each do |post| %>
                    <div data-controller="comments">
                      <div class="comment-main-level">
                      <%= link_to user_path(post.user_id) do %>
                        <div class="comment-avatar">
                            <%= cl_image_tag post.user.avatar.key, class: "avatar" %>
                        </div>
                        <div class="comment-box">
                          <div class="comment-head">
                            <h6 class="comment-name by-author"><%= post.user.first_name %> <%= post.user.last_name %></h6>
                      <% end %>
                            <span><%= (Date.today - post.created_at.to_date).to_i  %> days ago</span>
                            <i class="fa-solid fa-comment fa-xl" style="top: 14px; right: 5px;" data-action="click->comments#toggle">
                            </i>
                            <i>
                              <% like = current_user.likes.find_by(post: post) %>
                              <% if like.nil? %>
                                <%= button_to likes_path,
                                              params: { like: { post_id: post.id } },
                                              style:"border: none; background: none; width: 16px;",
                                              remote: true,
                                              method: :post do %>
                                  <i class="fa-solid fa-hand-peace fa-xl" style="top: -4px;"></i>
                                <% end %>
                              <% else %>
                                <%= button_to like_path(like),
                                              style:"border: none; background: none; width: 16px;",
                                              method: :delete do %>
                                  <i class="fa-solid fa-hand-peace fa-xl" style="color: #ff0000; top: -4px;"></i>
                                <% end %>
                              <% end %>
                            </i>
                            <i style="right: 8px;top: 5px;"><%= post.likes.count %></i>
                          </div>
                          <div class="comment-content">
                            <%= post.content %>
                          </div>
                        </div>
                      </div>
                      <ul class="comments-list reply-list">
                          <% post.comments.each do |comment| %>
                            <li>
                              <div class="comment-avatar">
                                <%= link_to user_path(comment.user_id) do %>
                                  <%= cl_image_tag comment.user.avatar.key, class: "avatar" %>
                              </div>
                              <div class="comment-box">
                                <div class="comment-head">
                                  <h6 class="comment-name">
                                    <%= comment.user.first_name %> <%= comment.user.last_name %>
                                <% end %>
                                    <span class="float-none mx-2">
                                      <%= (Date.today - comment.created_at.to_date).to_i %> days ago
                                    </span>
                                </div>
                                <div class="comment-content">
                                  <%= comment.content %>
                                </div>
                              </div>
                          <% end %>
                            <div data-comments-target="form" class="d-none">
                              <%= simple_form_for [post, @comment] do |f| %>
                                <%= f.input :content, label: "Write a comment", :required => false %>
                                <%= f.submit class: "button-50" %>
                              <% end %>
                            </div>
                            </li>
                      </ul>
                    </div>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-4 d-grid">
        <div class="card-helper p-2">
          <div class="owner my-3">
            <h2>Owner</h2>
            <div class="d-flex flex-column px-4 py-1 align-items-start">
            <%= link_to user_path(@event.user_id) do %>
              <p>
                <%= cl_image_tag @event.user.avatar.key, class: "avatar-large mx-2" %> <%= @event.user.first_name %> <%= @event.user.last_name %>
              </p>
            <% end %>
            </div>
          </div>
          <div class="helper">
            <h2 class="py-3">Helpers</h2>
              <div class="d-flex flex-column px-4 py-1 align-items-start">
                <% @participants.each do |participant| %>
                <%= link_to user_path(participant.user_id) do %>
                  <p>
                  <%= cl_image_tag participant.user.avatar.key, class: "avatar-large mx-2" %> <%= participant.user.first_name %> <%= participant.user.last_name %>
                  </p>
                <% end %>
                <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>